CREATE SINK CONNECTOR PRODUCTS_SINK_CONNECTOR WITH (
   'connector.class' = 'io.confluent.connect.jdbc.JdbcSinkConnector',
   'connection.url' = 'jdbc:postgresql://${env:<ignore>:postgres_hostname}:5432/${env:<ignore>:postgres_dbname}?currentSchema=master',
   'connection.user' = '${env:<ignore>:postgres_user}',
   'connection.password' = '${env:<ignore>:postgres_password}',
   'topics' = 'user_details_final',
   'max.retries'= 3,
   'auto.create' = 'true',
   'auto.evolve' = 'true',
   'insert.mode' = 'upsert',
   'pk.mode' = 'record_key',
   'pk.fields' = 'USERNAME',
   'delete.enabled'= 'true',
   'value.converter.schema.registry.url'='${env:<ignore>:CONNECT_SCHEMA_REGISTRY_URL}',
   'key.converter.schema.registry.url'='${env:<ignore>:CONNECT_SCHEMA_REGISTRY_URL}',
   'key.converter'='io.confluent.connect.avro.AvroConverter',
   'value.converter'='io.confluent.connect.avro.AvroConverter',
   'quote.sql.identifiers'='never',
   'errors.tolerance'='all',
   'errors.deadletterqueue.topic.name' = 'user_details_final_dlq',
   'errors.deadletterqueue.topic.replication.factor'= -1,
   'errors.log.include.messages' = true,
   'errors.log.enable' = true,
   'errors.deadletterqueue.context.headers.enable' = true
);