spring:
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672

rabbitmq:
  queue:
    user:
      name: "user"
      exchange: "user.exchange"
      routing-key: "user.key"
  properties:
    region: ap-south-1
    "[registry.name]": joe-kafka-schema-registry
    schemaAutoRegistrationEnabled: true
    avroRecordType: SPECIFIC_RECORD
    userAgentApp: rabbitmq
    tags:
      component: java-consumer-producer-service
      environment: sandbox

aws:
  auth:
    profile: tw-beach