spring:
  rabbitmq:
    host: localhost
    username: user
    password: password
    port: 5672

rabbitmq:
  producer-queue:
    user:
      name: "user-producer-queue"
      exchange: "user.exchange"
      routing-key: "user.key"
  consumer-queue:
    user:
      name: "user-consumer-queue"
      exchange: "user.exchange"
      routing-key: "user.key"
  properties:
    region: ap-south-1
    "[registry.name]": joe-kafka-schema-registry
    schemaAutoRegistrationEnabled: true
    avroRecordType: SPECIFIC_RECORD
    userAgentApp: rabbitmq
    compatibility: FULL_ALL
    description:
    tags:
      component: java-consumer-producer
      environment: sandbox
    metadata:
      service: java-consumer-producer-service

aws:
  auth:
    profile: tw-beach