CREATE SOURCE CONNECTOR MYSQL_SOURCE_CONNECTOR WITH(
    'connector.class'='io.debezium.connector.mysql.MySqlConnector',
    'tasks.max'='1',

    'database.hostname'='${env:<ignore>:mysql_hostname}',
    'database.port'=3306,
    'database.user'='${env:<ignore>:mysql_user}',
    'database.password'='${env:<ignore>:mysql_password}',
    'database.include.list'='${env:<ignore>:mysql_dbname}',
    'database.server.id'='1',
    'database.server.name'='mysql',
    'database.history.kafka.bootstrap.servers'='${env:<ignore>:CONNECT_BOOTSTRAP_SERVERS}',
    'database.history.kafka.topic'='mysql_schema_inventory',
    'include.schema.changes'=true,
    'table.include.list'='root.customer',

    'internal.key.converter'='org.apache.kafka.connect.json.JsonConverter',
    'internal.key.converter.schemas.enable'='false',
    'internal.value.converter'='org.apache.kafka.connect.json.JsonConverter',
    'internal.value.converter.schemas.enable'='false',
    'key.converter'='io.confluent.connect.avro.AvroConverter',
    'key.converter.schemas.enable'=true,
    'key.converter.enhanced.avro.schema.support'=true,
    'key.converter.schema.registry.url'='${env:<ignore>:CONNECT_SCHEMA_REGISTRY_URL}',
    'value.converter'='io.confluent.connect.avro.AvroConverter',
    'value.converter.schemas.enable'=true,
    'value.converter.enhanced.avro.schema.support'=true,
    'value.converter.schema.registry.url'='${env:<ignore>:CONNECT_SCHEMA_REGISTRY_URL}',

    'transforms'='filter,unwrap,route',
    'transforms.filter.type'='com.joe.connect.transformer.BeforeAfterCompareFilter',
    'transforms.filter.exclude.column.list'='name,phone_number',
    'transforms.unwrap.type'='io.debezium.transforms.ExtractNewRecordState',
    'transforms.unwrap.drop.tombstones'=false,
    'transforms.unwrap.delete.handling.mode'='rewrite',
    'transforms.route.type'='org.apache.kafka.connect.transforms.RegexRouter',
    'transforms.route.regex'='([^.]+)\.([^.]+)\.([^.]+)',
    'transforms.route.replacement'='$3',
    'snapshot.mode'='when_needed',
    'tombstones.on.delete'=true,

    'topic.creation.default.cleanup.policy'='compact',
    'topic.creation.default.replication.factor'=-1,
    'topic.creation.default.partitions'=1
);
